/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

/*
 * Copyright (C) 2019 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.sdk.v3.payments;


import com.clover.sdk.GenericClient;
import com.clover.sdk.GenericParcelable;

/**
 * This is an auto-generated Clover data object.
 * <p>
 * Country-specific denomination configuration
 * <p>
 * <h3>Fields</h3>
 * <ul>
 * <li>{@link #getCountryCode countryCode}</li>
 * <li>{@link #getUnits units}</li>
 * </ul>
 */
@SuppressWarnings("all")
public class CountryDenomination extends GenericParcelable implements com.clover.sdk.v3.Validator, com.clover.sdk.JSONifiable {

  /**
   * ISO country code (e.g., JP, IN, AU, SG)
   */
  public String getCountryCode() {
    return genClient.cacheGet(CacheKey.countryCode);
  }

  /**
   * Array of denomination units as strings (e.g., '10000', '5000', '0.50')
   */
  public java.util.List<String> getUnits() {
    return genClient.cacheGet(CacheKey.units);
  }




  private enum CacheKey implements com.clover.sdk.ExtractionStrategyEnum {
    countryCode
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(String.class)),
    units
        (com.clover.sdk.extractors.BasicListExtractionStrategy.instance(String.class)),
      ;

    private final com.clover.sdk.extractors.ExtractionStrategy extractionStrategy;

    private CacheKey(com.clover.sdk.extractors.ExtractionStrategy s) {
      extractionStrategy = s;
    }

    @Override
    public com.clover.sdk.extractors.ExtractionStrategy getExtractionStrategy() {
      return extractionStrategy;
    }
  }

  private final GenericClient<CountryDenomination> genClient;

  /**
   * Constructs a new empty instance.
   */
  public CountryDenomination() {
    genClient = new GenericClient<CountryDenomination>(this);
  }

  @Override
  protected GenericClient getGenericClient() {
    return genClient;
  }

  /**
   * Constructs a new empty instance.
   */
  protected CountryDenomination(boolean noInit) {
    genClient = null;
  }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public CountryDenomination(String json) throws IllegalArgumentException {
    this();
    genClient.initJsonObject(json);
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public CountryDenomination(org.json.JSONObject jsonObject) {
    this();
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public CountryDenomination(CountryDenomination src) {
    this();
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }

  @Override
  public void validate() {
  }

  /** Checks whether the 'countryCode' field is set and is not null */
  public boolean isNotNullCountryCode() {
    return genClient.cacheValueIsNotNull(CacheKey.countryCode);
  }

  /** Checks whether the 'units' field is set and is not null */
  public boolean isNotNullUnits() {
    return genClient.cacheValueIsNotNull(CacheKey.units);
  }

  /** Checks whether the 'units' field is set and is not null and is not empty */
  public boolean isNotEmptyUnits() { return isNotNullUnits() && !getUnits().isEmpty(); }



  /** Checks whether the 'countryCode' field has been set, however the value could be null */
  public boolean hasCountryCode() {
    return genClient.cacheHasKey(CacheKey.countryCode);
  }

  /** Checks whether the 'units' field has been set, however the value could be null */
  public boolean hasUnits() {
    return genClient.cacheHasKey(CacheKey.units);
  }


  /**
   * Sets the field 'countryCode'.
   */
  public CountryDenomination setCountryCode(String countryCode) {
    return genClient.setOther(countryCode, CacheKey.countryCode);
  }

  /**
   * Sets the field 'units'.
   *
   * Nulls in the given List are skipped. List parameter is copied, so it will not reflect any changes, but objects inside it will.
   */
  public CountryDenomination setUnits(java.util.List<String> units) {
    return genClient.setArrayOther(units, CacheKey.units);
  }


  /** Clears the 'countryCode' field, the 'has' method for this field will now return false */
  public void clearCountryCode() {
    genClient.clear(CacheKey.countryCode);
  }
  /** Clears the 'units' field, the 'has' method for this field will now return false */
  public void clearUnits() {
    genClient.clear(CacheKey.units);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public CountryDenomination copyChanges() {
    CountryDenomination copy = new CountryDenomination();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(CountryDenomination src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new CountryDenomination(src).getJSONObject(), src.genClient);
    }
  }

  public static final android.os.Parcelable.Creator<CountryDenomination> CREATOR = new android.os.Parcelable.Creator<CountryDenomination>() {
    @Override
    public CountryDenomination createFromParcel(android.os.Parcel in) {
      CountryDenomination instance = new CountryDenomination(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public CountryDenomination[] newArray(int size) {
      return new CountryDenomination[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<CountryDenomination> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<CountryDenomination>() {
    public Class<CountryDenomination> getCreatedClass() {
      return CountryDenomination.class;
    }

    @Override
    public CountryDenomination create(org.json.JSONObject jsonObject) {
      return new CountryDenomination(jsonObject);
    }
  };

  public interface Constraints {
    public static final boolean COUNTRYCODE_IS_REQUIRED = false;
    public static final boolean UNITS_IS_REQUIRED = false;
  }

}
