/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

/*
 * Copyright (C) 2019 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.sdk.v3.shipping;


import com.clover.sdk.GenericClient;
import com.clover.sdk.GenericParcelable;

/**
 * This is an auto-generated Clover data object.
 * <p>
 * Individual shipping label associated with an order
 * <p>
 * <h3>Fields</h3>
 * <ul>
 * <li>{@link #getLabelUuid labelUuid}</li>
 * <li>{@link #getTrackingNumber trackingNumber}</li>
 * <li>{@link #getTrackingUrl trackingUrl}</li>
 * <li>{@link #getTrackingStatus trackingStatus}</li>
 * <li>{@link #getCostAmount costAmount}</li>
 * <li>{@link #getLabelUrl labelUrl}</li>
 * <li>{@link #getPurchasedAt purchasedAt}</li>
 * </ul>
 */
@SuppressWarnings("all")
public class ShippingLabel extends GenericParcelable implements com.clover.sdk.v3.Validator, com.clover.sdk.JSONifiable {

  /**
   * Unique identifier for the label
   */
  public String getLabelUuid() {
    return genClient.cacheGet(CacheKey.labelUuid);
  }

  /**
   * Carrier-assigned tracking number
   */
  public String getTrackingNumber() {
    return genClient.cacheGet(CacheKey.trackingNumber);
  }

  /**
   * URL to track the shipment on the carrier website
   */
  public String getTrackingUrl() {
    return genClient.cacheGet(CacheKey.trackingUrl);
  }

  /**
   * Current tracking status of the label
   */
  public String getTrackingStatus() {
    return genClient.cacheGet(CacheKey.trackingStatus);
  }

  /**
   * Cost of the shipping label in the merchant currency
   */
  public Double getCostAmount() {
    return genClient.cacheGet(CacheKey.costAmount);
  }

  /**
   * URL to download the shipping label PDF
   */
  public String getLabelUrl() {
    return genClient.cacheGet(CacheKey.labelUrl);
  }

  /**
   * Timestamp (ms since epoch) when the label was purchased
   */
  public Long getPurchasedAt() {
    return genClient.cacheGet(CacheKey.purchasedAt);
  }




  private enum CacheKey implements com.clover.sdk.ExtractionStrategyEnum {
    labelUuid
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(String.class)),
    trackingNumber
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(String.class)),
    trackingUrl
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(String.class)),
    trackingStatus
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(String.class)),
    costAmount
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(Double.class)),
    labelUrl
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(String.class)),
    purchasedAt
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(Long.class)),
      ;

    private final com.clover.sdk.extractors.ExtractionStrategy extractionStrategy;

    private CacheKey(com.clover.sdk.extractors.ExtractionStrategy s) {
      extractionStrategy = s;
    }

    @Override
    public com.clover.sdk.extractors.ExtractionStrategy getExtractionStrategy() {
      return extractionStrategy;
    }
  }

  private final GenericClient<ShippingLabel> genClient;

  /**
   * Constructs a new empty instance.
   */
  public ShippingLabel() {
    genClient = new GenericClient<ShippingLabel>(this);
  }

  @Override
  protected GenericClient getGenericClient() {
    return genClient;
  }

  /**
   * Constructs a new empty instance.
   */
  protected ShippingLabel(boolean noInit) {
    genClient = null;
  }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public ShippingLabel(String json) throws IllegalArgumentException {
    this();
    genClient.initJsonObject(json);
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public ShippingLabel(org.json.JSONObject jsonObject) {
    this();
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public ShippingLabel(ShippingLabel src) {
    this();
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }

  @Override
  public void validate() {
  }

  /** Checks whether the 'labelUuid' field is set and is not null */
  public boolean isNotNullLabelUuid() {
    return genClient.cacheValueIsNotNull(CacheKey.labelUuid);
  }

  /** Checks whether the 'trackingNumber' field is set and is not null */
  public boolean isNotNullTrackingNumber() {
    return genClient.cacheValueIsNotNull(CacheKey.trackingNumber);
  }

  /** Checks whether the 'trackingUrl' field is set and is not null */
  public boolean isNotNullTrackingUrl() {
    return genClient.cacheValueIsNotNull(CacheKey.trackingUrl);
  }

  /** Checks whether the 'trackingStatus' field is set and is not null */
  public boolean isNotNullTrackingStatus() {
    return genClient.cacheValueIsNotNull(CacheKey.trackingStatus);
  }

  /** Checks whether the 'costAmount' field is set and is not null */
  public boolean isNotNullCostAmount() {
    return genClient.cacheValueIsNotNull(CacheKey.costAmount);
  }

  /** Checks whether the 'labelUrl' field is set and is not null */
  public boolean isNotNullLabelUrl() {
    return genClient.cacheValueIsNotNull(CacheKey.labelUrl);
  }

  /** Checks whether the 'purchasedAt' field is set and is not null */
  public boolean isNotNullPurchasedAt() {
    return genClient.cacheValueIsNotNull(CacheKey.purchasedAt);
  }



  /** Checks whether the 'labelUuid' field has been set, however the value could be null */
  public boolean hasLabelUuid() {
    return genClient.cacheHasKey(CacheKey.labelUuid);
  }

  /** Checks whether the 'trackingNumber' field has been set, however the value could be null */
  public boolean hasTrackingNumber() {
    return genClient.cacheHasKey(CacheKey.trackingNumber);
  }

  /** Checks whether the 'trackingUrl' field has been set, however the value could be null */
  public boolean hasTrackingUrl() {
    return genClient.cacheHasKey(CacheKey.trackingUrl);
  }

  /** Checks whether the 'trackingStatus' field has been set, however the value could be null */
  public boolean hasTrackingStatus() {
    return genClient.cacheHasKey(CacheKey.trackingStatus);
  }

  /** Checks whether the 'costAmount' field has been set, however the value could be null */
  public boolean hasCostAmount() {
    return genClient.cacheHasKey(CacheKey.costAmount);
  }

  /** Checks whether the 'labelUrl' field has been set, however the value could be null */
  public boolean hasLabelUrl() {
    return genClient.cacheHasKey(CacheKey.labelUrl);
  }

  /** Checks whether the 'purchasedAt' field has been set, however the value could be null */
  public boolean hasPurchasedAt() {
    return genClient.cacheHasKey(CacheKey.purchasedAt);
  }


  /**
   * Sets the field 'labelUuid'.
   */
  public ShippingLabel setLabelUuid(String labelUuid) {
    return genClient.setOther(labelUuid, CacheKey.labelUuid);
  }

  /**
   * Sets the field 'trackingNumber'.
   */
  public ShippingLabel setTrackingNumber(String trackingNumber) {
    return genClient.setOther(trackingNumber, CacheKey.trackingNumber);
  }

  /**
   * Sets the field 'trackingUrl'.
   */
  public ShippingLabel setTrackingUrl(String trackingUrl) {
    return genClient.setOther(trackingUrl, CacheKey.trackingUrl);
  }

  /**
   * Sets the field 'trackingStatus'.
   */
  public ShippingLabel setTrackingStatus(String trackingStatus) {
    return genClient.setOther(trackingStatus, CacheKey.trackingStatus);
  }

  /**
   * Sets the field 'costAmount'.
   */
  public ShippingLabel setCostAmount(Double costAmount) {
    return genClient.setOther(costAmount, CacheKey.costAmount);
  }

  /**
   * Sets the field 'labelUrl'.
   */
  public ShippingLabel setLabelUrl(String labelUrl) {
    return genClient.setOther(labelUrl, CacheKey.labelUrl);
  }

  /**
   * Sets the field 'purchasedAt'.
   */
  public ShippingLabel setPurchasedAt(Long purchasedAt) {
    return genClient.setOther(purchasedAt, CacheKey.purchasedAt);
  }


  /** Clears the 'labelUuid' field, the 'has' method for this field will now return false */
  public void clearLabelUuid() {
    genClient.clear(CacheKey.labelUuid);
  }
  /** Clears the 'trackingNumber' field, the 'has' method for this field will now return false */
  public void clearTrackingNumber() {
    genClient.clear(CacheKey.trackingNumber);
  }
  /** Clears the 'trackingUrl' field, the 'has' method for this field will now return false */
  public void clearTrackingUrl() {
    genClient.clear(CacheKey.trackingUrl);
  }
  /** Clears the 'trackingStatus' field, the 'has' method for this field will now return false */
  public void clearTrackingStatus() {
    genClient.clear(CacheKey.trackingStatus);
  }
  /** Clears the 'costAmount' field, the 'has' method for this field will now return false */
  public void clearCostAmount() {
    genClient.clear(CacheKey.costAmount);
  }
  /** Clears the 'labelUrl' field, the 'has' method for this field will now return false */
  public void clearLabelUrl() {
    genClient.clear(CacheKey.labelUrl);
  }
  /** Clears the 'purchasedAt' field, the 'has' method for this field will now return false */
  public void clearPurchasedAt() {
    genClient.clear(CacheKey.purchasedAt);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public ShippingLabel copyChanges() {
    ShippingLabel copy = new ShippingLabel();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(ShippingLabel src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new ShippingLabel(src).getJSONObject(), src.genClient);
    }
  }

  public static final android.os.Parcelable.Creator<ShippingLabel> CREATOR = new android.os.Parcelable.Creator<ShippingLabel>() {
    @Override
    public ShippingLabel createFromParcel(android.os.Parcel in) {
      ShippingLabel instance = new ShippingLabel(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public ShippingLabel[] newArray(int size) {
      return new ShippingLabel[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<ShippingLabel> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<ShippingLabel>() {
    public Class<ShippingLabel> getCreatedClass() {
      return ShippingLabel.class;
    }

    @Override
    public ShippingLabel create(org.json.JSONObject jsonObject) {
      return new ShippingLabel(jsonObject);
    }
  };

  public interface Constraints {
    public static final boolean LABELUUID_IS_REQUIRED = false;
    public static final boolean TRACKINGNUMBER_IS_REQUIRED = false;
    public static final boolean TRACKINGURL_IS_REQUIRED = false;
    public static final boolean TRACKINGSTATUS_IS_REQUIRED = false;
    public static final boolean COSTAMOUNT_IS_REQUIRED = false;
    public static final boolean LABELURL_IS_REQUIRED = false;
    public static final boolean PURCHASEDAT_IS_REQUIRED = false;
  }

}
