/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


package com.clover.sdk.v3.developer;

@SuppressWarnings("all")
public enum DeveloperBillingStatus {
  PENDING, APPROVED, DECLINED, ERROR;
}
