/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */


/*
 * Copyright (C) 2019 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.sdk.v3.remotepay;

import android.os.Parcelable;
import android.os.Parcel;

/**
 * This is an auto-generated Clover data enum.
 * We can not include WELCOME_SCREEN, THANKYOU_SCREEN, DISPLAY_MESSAGE, DISPLAY_ORDER until we can filter them out in remote-pay before they go through the interface to older versions of the sdk
 */
@SuppressWarnings("all")
public enum DeviceEventState implements Parcelable {
  ADD_SIGNATURE, ADD_SIGNATURE_CANCEL_CONFIRM, ADD_TIP, APPROVE_ELV_LIMIT_OVERRIDE, APPROVED, CANCELED, CASHBACK_CONFIRM, CASHBACK_SELECT, CONFIGURING, CONFIRM_AMOUNT, CONFIRM_DUPLICATE_CHECK, CONFIRM_PARTIAL_AUTH, CONFIRMATION_ACTIVITY, CONTACTLESS_TAP_REQUIRED, CUSTOM_ACTIVITY, CUSTOM_TIP_AMOUNT, CUSTOMER_TENDER, DCC_HOST_REQUEST, DECLINED, ENTER_INSTALLMENT_CODE, ENTER_INSTALLMENTS, ENTER_PAN_LAST_FOUR, ERROR_SCREEN, FAILED, FATAL, FISCAL_INVOICE_NUMBER, FORCE_ACCEPTANCE, HANDLE_TENDER, INPUT_ERROR, INVALID_GIFT_CARD_SCANNED, LOYALTY_DISPLAYING, MANUAL_CARD_CVV, MANUAL_CARD_CVV_UNREADABLE, MANUAL_CARD_EXPIRATION, MANUAL_CARD_NUMBER, MANUAL_ENTRY_FALLBACK, OFFLINE_PAYMENT_CONFIRM, PACKET_EXCEPTION, PERSONAL_ID_ENTRY, PERSONAL_ID_ENTRY_PAS, PIN_BYPASS_CONFIRM, PIN_PAD, PROCESS_GLOBAL_BIN_INFO, PROCESS_PURCHASING_CARD_TYPE, PROCESSING, PROCESSING_CREDIT, PROCESSING_GO_ONLINE, PROCESSING_SWIPE, RECEIPT_OPTIONS, REMOVE_CARD, RETURN_TO_MERCHANT, SCAN_LPM_QR_CODE, SELECT_ACCOUNT, SELECT_APPLICATION, SELECT_COBRAND_CARDTYPE, SELECT_DCC, SELECT_INSTALLMENT_PLAN, SELECT_LANGUAGE, SELECT_MULTI_MID, SELECT_TIP, SELECT_WITHDRAW_FROM_ACCOUNT, SENSORY_EXPERIENCE, SHOW_SEPA_MANDAT, SIGNATURE_CUSTOMER_MODE, SIGNATURE_ON_SCREEN_FALLBACK, SIGNATURE_REJECT, START, START_QR_CODE_MODE, START_SCAN_GIFT_CARD, STARTING_CUSTOM_ACTIVITY, SWIPE_CVV_ENTRY, TIMED_OUT, TRY_AGAIN, VERIFY_SIGNATURE_ON_PAPER, VERIFY_SIGNATURE_ON_PAPER_CONFIRM_VOID, VERIFY_SIGNATURE_ON_SCREEN, VERIFY_SIGNATURE_ON_SCREEN_CONFIRM_VOID, VERIFY_SURCHARGES, VOICE_REFERRAL_RESULT, VOID_CONFIRM, VOIDED, WAIT_FOR_REMOTE_PAY_APPROVAL;

  @Override
  public int describeContents() {
    return 0;
  }

  @Override
  public void writeToParcel(final Parcel dest, final int flags) {
    dest.writeString(name());
  }

  public static final Creator<DeviceEventState> CREATOR = new Creator<DeviceEventState>() {
    @Override
    public DeviceEventState createFromParcel(final Parcel source) {
      return DeviceEventState.valueOf(source.readString());
    }

    @Override
    public DeviceEventState[] newArray(final int size) {
      return new DeviceEventState[size];
    }
  };
}
