/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

/*
 * Copyright (C) 2019 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.sdk.v3.inventory;


import androidx.annotation.Nullable;

import com.clover.sdk.GenericClient;
import com.clover.sdk.GenericParcelable;

/**
 * This is an auto-generated Clover data object.
 * <p>
 * Association between an item entitlement plan and a menu through which it is sold
 * <p>
 * <h3>Fields</h3>
 * <ul>
 * <li>{@link #getId id}</li>
 * <li>{@link #getItemEntitlementPlan itemEntitlementPlan}</li>
 * <li>{@link #getMenu menu}</li>
 * <li>{@link #getCreatedTime createdTime}</li>
 * <li>{@link #getModifiedTime modifiedTime}</li>
 * </ul>
 * <p>
 * @see com.clover.sdk.v3.inventory.IInventoryService
 */
@SuppressWarnings("all")
public class ItemEntitlementPlanAvailabilityMenu extends GenericParcelable implements com.clover.sdk.v3.Validator, com.clover.sdk.JSONifiable {

  /**
   * Unique identifier
   */
  @Nullable
  public String getId() {
    return genClient.cacheGet(CacheKey.id);
  }

  /**
   * Reference to the item entitlement plan
   */
  @Nullable
  public com.clover.sdk.v3.base.Reference getItemEntitlementPlan() {
    return genClient.cacheGet(CacheKey.itemEntitlementPlan);
  }

  /**
   * Reference to the menu through which this plan is sold
   */
  @Nullable
  public com.clover.sdk.v3.base.Reference getMenu() {
    return genClient.cacheGet(CacheKey.menu);
  }

  /**
   * Timestamp when this association was created
   */
  @Nullable
  public Long getCreatedTime() {
    return genClient.cacheGet(CacheKey.createdTime);
  }

  /**
   * Timestamp when this association was last modified
   */
  @Nullable
  public Long getModifiedTime() {
    return genClient.cacheGet(CacheKey.modifiedTime);
  }




  private enum CacheKey implements com.clover.sdk.ExtractionStrategyEnum {
    id
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(String.class)),
    itemEntitlementPlan
        (com.clover.sdk.extractors.RecordExtractionStrategy.instance(com.clover.sdk.v3.base.Reference.JSON_CREATOR)),
    menu
        (com.clover.sdk.extractors.RecordExtractionStrategy.instance(com.clover.sdk.v3.base.Reference.JSON_CREATOR)),
    createdTime
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(Long.class)),
    modifiedTime
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(Long.class)),
      ;

    private final com.clover.sdk.extractors.ExtractionStrategy extractionStrategy;

    private CacheKey(com.clover.sdk.extractors.ExtractionStrategy s) {
      extractionStrategy = s;
    }

    @Override
    public com.clover.sdk.extractors.ExtractionStrategy getExtractionStrategy() {
      return extractionStrategy;
    }
  }

  private final GenericClient<ItemEntitlementPlanAvailabilityMenu> genClient;

  /**
   * Constructs a new empty instance.
   */
  public ItemEntitlementPlanAvailabilityMenu() {
    genClient = new GenericClient<ItemEntitlementPlanAvailabilityMenu>(this);
  }

  @Override
  protected GenericClient getGenericClient() {
    return genClient;
  }

  /**
   * Constructs a new empty instance.
   */
  protected ItemEntitlementPlanAvailabilityMenu(boolean noInit) {
    genClient = null;
  }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public ItemEntitlementPlanAvailabilityMenu(String json) throws IllegalArgumentException {
    this();
    genClient.initJsonObject(json);
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public ItemEntitlementPlanAvailabilityMenu(org.json.JSONObject jsonObject) {
    this();
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public ItemEntitlementPlanAvailabilityMenu(ItemEntitlementPlanAvailabilityMenu src) {
    this();
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }

  @Override
  public void validate() {
    genClient.validateCloverId(CacheKey.id, getId());
    genClient.validateReferences(CacheKey.itemEntitlementPlan);
    genClient.validateReferences(CacheKey.menu);
  }

  /** Checks whether the 'id' field is set and is not null */
  public boolean isNotNullId() {
    return genClient.cacheValueIsNotNull(CacheKey.id);
  }

  /** Checks whether the 'itemEntitlementPlan' field is set and is not null */
  public boolean isNotNullItemEntitlementPlan() {
    return genClient.cacheValueIsNotNull(CacheKey.itemEntitlementPlan);
  }

  /** Checks whether the 'menu' field is set and is not null */
  public boolean isNotNullMenu() {
    return genClient.cacheValueIsNotNull(CacheKey.menu);
  }

  /** Checks whether the 'createdTime' field is set and is not null */
  public boolean isNotNullCreatedTime() {
    return genClient.cacheValueIsNotNull(CacheKey.createdTime);
  }

  /** Checks whether the 'modifiedTime' field is set and is not null */
  public boolean isNotNullModifiedTime() {
    return genClient.cacheValueIsNotNull(CacheKey.modifiedTime);
  }



  /** Checks whether the 'id' field has been set, however the value could be null */
  public boolean hasId() {
    return genClient.cacheHasKey(CacheKey.id);
  }

  /** Checks whether the 'itemEntitlementPlan' field has been set, however the value could be null */
  public boolean hasItemEntitlementPlan() {
    return genClient.cacheHasKey(CacheKey.itemEntitlementPlan);
  }

  /** Checks whether the 'menu' field has been set, however the value could be null */
  public boolean hasMenu() {
    return genClient.cacheHasKey(CacheKey.menu);
  }

  /** Checks whether the 'createdTime' field has been set, however the value could be null */
  public boolean hasCreatedTime() {
    return genClient.cacheHasKey(CacheKey.createdTime);
  }

  /** Checks whether the 'modifiedTime' field has been set, however the value could be null */
  public boolean hasModifiedTime() {
    return genClient.cacheHasKey(CacheKey.modifiedTime);
  }


  /**
   * Sets the field 'id'.
   */
  public ItemEntitlementPlanAvailabilityMenu setId(@Nullable String id) {
    return genClient.setOther(id, CacheKey.id);
  }

  /**
   * Sets the field 'itemEntitlementPlan'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public ItemEntitlementPlanAvailabilityMenu setItemEntitlementPlan(@Nullable com.clover.sdk.v3.base.Reference itemEntitlementPlan) {
    return genClient.setRecord(itemEntitlementPlan, CacheKey.itemEntitlementPlan);
  }

  /**
   * Sets the field 'menu'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public ItemEntitlementPlanAvailabilityMenu setMenu(@Nullable com.clover.sdk.v3.base.Reference menu) {
    return genClient.setRecord(menu, CacheKey.menu);
  }

  /**
   * Sets the field 'createdTime'.
   */
  public ItemEntitlementPlanAvailabilityMenu setCreatedTime(@Nullable Long createdTime) {
    return genClient.setOther(createdTime, CacheKey.createdTime);
  }

  /**
   * Sets the field 'modifiedTime'.
   */
  public ItemEntitlementPlanAvailabilityMenu setModifiedTime(@Nullable Long modifiedTime) {
    return genClient.setOther(modifiedTime, CacheKey.modifiedTime);
  }


  /** Clears the 'id' field, the 'has' method for this field will now return false */
  public void clearId() {
    genClient.clear(CacheKey.id);
  }
  /** Clears the 'itemEntitlementPlan' field, the 'has' method for this field will now return false */
  public void clearItemEntitlementPlan() {
    genClient.clear(CacheKey.itemEntitlementPlan);
  }
  /** Clears the 'menu' field, the 'has' method for this field will now return false */
  public void clearMenu() {
    genClient.clear(CacheKey.menu);
  }
  /** Clears the 'createdTime' field, the 'has' method for this field will now return false */
  public void clearCreatedTime() {
    genClient.clear(CacheKey.createdTime);
  }
  /** Clears the 'modifiedTime' field, the 'has' method for this field will now return false */
  public void clearModifiedTime() {
    genClient.clear(CacheKey.modifiedTime);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public ItemEntitlementPlanAvailabilityMenu copyChanges() {
    ItemEntitlementPlanAvailabilityMenu copy = new ItemEntitlementPlanAvailabilityMenu();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(ItemEntitlementPlanAvailabilityMenu src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new ItemEntitlementPlanAvailabilityMenu(src).getJSONObject(), src.genClient);
    }
  }

  public static final android.os.Parcelable.Creator<ItemEntitlementPlanAvailabilityMenu> CREATOR = new android.os.Parcelable.Creator<ItemEntitlementPlanAvailabilityMenu>() {
    @Override
    public ItemEntitlementPlanAvailabilityMenu createFromParcel(android.os.Parcel in) {
      ItemEntitlementPlanAvailabilityMenu instance = new ItemEntitlementPlanAvailabilityMenu(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public ItemEntitlementPlanAvailabilityMenu[] newArray(int size) {
      return new ItemEntitlementPlanAvailabilityMenu[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<ItemEntitlementPlanAvailabilityMenu> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<ItemEntitlementPlanAvailabilityMenu>() {
    public Class<ItemEntitlementPlanAvailabilityMenu> getCreatedClass() {
      return ItemEntitlementPlanAvailabilityMenu.class;
    }

    @Override
    public ItemEntitlementPlanAvailabilityMenu create(org.json.JSONObject jsonObject) {
      return new ItemEntitlementPlanAvailabilityMenu(jsonObject);
    }
  };

  public interface Constraints {
    public static final boolean ID_IS_REQUIRED = false;
    public static final long ID_MAX_LEN = 13;
    public static final boolean ITEMENTITLEMENTPLAN_IS_REQUIRED = false;
    public static final boolean MENU_IS_REQUIRED = false;
    public static final boolean CREATEDTIME_IS_REQUIRED = false;
    public static final boolean MODIFIEDTIME_IS_REQUIRED = false;
  }

}
