/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

/*
 * Copyright (C) 2019 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.sdk.v3.report;

import com.clover.sdk.GenericClient;
import com.clover.sdk.GenericParcelable;

/**
 * This is an auto-generated Clover data object.
 * <p>
 * <h3>Fields</h3>
 * <ul>
 * <li>{@link #getId id}</li>
 * <li>{@link #getSummaryObject summaryObject}</li>
 * <li>{@link #getPaymentsSummary paymentsSummary}</li>
 * <li>{@link #getRefundsSummary refundsSummary}</li>
 * <li>{@link #getCreditsSummary creditsSummary}</li>
 * <li>{@link #getDiscountsSummary discountsSummary}</li>
 * </ul>
 */
@SuppressWarnings("all")
public class SummaryGroup extends GenericParcelable implements com.clover.sdk.v3.Validator, com.clover.sdk.JSONifiable {

  public java.lang.String getId() {
    return genClient.cacheGet(CacheKey.id);
  }

  public com.clover.sdk.v3.base.Reference getSummaryObject() {
    return genClient.cacheGet(CacheKey.summaryObject);
  }

  public com.clover.sdk.v3.report.Summary getPaymentsSummary() {
    return genClient.cacheGet(CacheKey.paymentsSummary);
  }

  public com.clover.sdk.v3.report.Summary getRefundsSummary() {
    return genClient.cacheGet(CacheKey.refundsSummary);
  }

  public com.clover.sdk.v3.report.Summary getCreditsSummary() {
    return genClient.cacheGet(CacheKey.creditsSummary);
  }

  public com.clover.sdk.v3.report.Summary getDiscountsSummary() {
    return genClient.cacheGet(CacheKey.discountsSummary);
  }




  private enum CacheKey implements com.clover.sdk.ExtractionStrategyEnum {
    id
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.String.class)),
    summaryObject
        (com.clover.sdk.extractors.RecordExtractionStrategy.instance(com.clover.sdk.v3.base.Reference.JSON_CREATOR)),
    paymentsSummary
        (com.clover.sdk.extractors.RecordExtractionStrategy.instance(com.clover.sdk.v3.report.Summary.JSON_CREATOR)),
    refundsSummary
        (com.clover.sdk.extractors.RecordExtractionStrategy.instance(com.clover.sdk.v3.report.Summary.JSON_CREATOR)),
    creditsSummary
        (com.clover.sdk.extractors.RecordExtractionStrategy.instance(com.clover.sdk.v3.report.Summary.JSON_CREATOR)),
    discountsSummary
        (com.clover.sdk.extractors.RecordExtractionStrategy.instance(com.clover.sdk.v3.report.Summary.JSON_CREATOR)),
      ;

    private final com.clover.sdk.extractors.ExtractionStrategy extractionStrategy;

    private CacheKey(com.clover.sdk.extractors.ExtractionStrategy s) {
      extractionStrategy = s;
    }

    @Override
    public com.clover.sdk.extractors.ExtractionStrategy getExtractionStrategy() {
      return extractionStrategy;
    }
  }

  private final GenericClient<SummaryGroup> genClient;

  /**
   * Constructs a new empty instance.
   */
  public SummaryGroup() {
    genClient = new GenericClient<SummaryGroup>(this);
  }

  @Override
  protected GenericClient getGenericClient() {
    return genClient;
  }

  /**
   * Constructs a new empty instance.
   */
  protected SummaryGroup(boolean noInit) {
    genClient = null;
  }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public SummaryGroup(String json) throws IllegalArgumentException {
    this();
    genClient.initJsonObject(json);
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public SummaryGroup(org.json.JSONObject jsonObject) {
    this();
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public SummaryGroup(SummaryGroup src) {
    this();
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }

  @Override
  public void validate() {
    genClient.validateReferences(CacheKey.summaryObject);
  }

  /** Checks whether the 'id' field is set and is not null */
  public boolean isNotNullId() {
    return genClient.cacheValueIsNotNull(CacheKey.id);
  }

  /** Checks whether the 'summaryObject' field is set and is not null */
  public boolean isNotNullSummaryObject() {
    return genClient.cacheValueIsNotNull(CacheKey.summaryObject);
  }

  /** Checks whether the 'paymentsSummary' field is set and is not null */
  public boolean isNotNullPaymentsSummary() {
    return genClient.cacheValueIsNotNull(CacheKey.paymentsSummary);
  }

  /** Checks whether the 'refundsSummary' field is set and is not null */
  public boolean isNotNullRefundsSummary() {
    return genClient.cacheValueIsNotNull(CacheKey.refundsSummary);
  }

  /** Checks whether the 'creditsSummary' field is set and is not null */
  public boolean isNotNullCreditsSummary() {
    return genClient.cacheValueIsNotNull(CacheKey.creditsSummary);
  }

  /** Checks whether the 'discountsSummary' field is set and is not null */
  public boolean isNotNullDiscountsSummary() {
    return genClient.cacheValueIsNotNull(CacheKey.discountsSummary);
  }



  /** Checks whether the 'id' field has been set, however the value could be null */
  public boolean hasId() {
    return genClient.cacheHasKey(CacheKey.id);
  }

  /** Checks whether the 'summaryObject' field has been set, however the value could be null */
  public boolean hasSummaryObject() {
    return genClient.cacheHasKey(CacheKey.summaryObject);
  }

  /** Checks whether the 'paymentsSummary' field has been set, however the value could be null */
  public boolean hasPaymentsSummary() {
    return genClient.cacheHasKey(CacheKey.paymentsSummary);
  }

  /** Checks whether the 'refundsSummary' field has been set, however the value could be null */
  public boolean hasRefundsSummary() {
    return genClient.cacheHasKey(CacheKey.refundsSummary);
  }

  /** Checks whether the 'creditsSummary' field has been set, however the value could be null */
  public boolean hasCreditsSummary() {
    return genClient.cacheHasKey(CacheKey.creditsSummary);
  }

  /** Checks whether the 'discountsSummary' field has been set, however the value could be null */
  public boolean hasDiscountsSummary() {
    return genClient.cacheHasKey(CacheKey.discountsSummary);
  }


  /**
   * Sets the field 'id'.
   */
  public SummaryGroup setId(java.lang.String id) {
    return genClient.setOther(id, CacheKey.id);
  }

  /**
   * Sets the field 'summaryObject'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public SummaryGroup setSummaryObject(com.clover.sdk.v3.base.Reference summaryObject) {
    return genClient.setRecord(summaryObject, CacheKey.summaryObject);
  }

  /**
   * Sets the field 'paymentsSummary'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public SummaryGroup setPaymentsSummary(com.clover.sdk.v3.report.Summary paymentsSummary) {
    return genClient.setRecord(paymentsSummary, CacheKey.paymentsSummary);
  }

  /**
   * Sets the field 'refundsSummary'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public SummaryGroup setRefundsSummary(com.clover.sdk.v3.report.Summary refundsSummary) {
    return genClient.setRecord(refundsSummary, CacheKey.refundsSummary);
  }

  /**
   * Sets the field 'creditsSummary'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public SummaryGroup setCreditsSummary(com.clover.sdk.v3.report.Summary creditsSummary) {
    return genClient.setRecord(creditsSummary, CacheKey.creditsSummary);
  }

  /**
   * Sets the field 'discountsSummary'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public SummaryGroup setDiscountsSummary(com.clover.sdk.v3.report.Summary discountsSummary) {
    return genClient.setRecord(discountsSummary, CacheKey.discountsSummary);
  }


  /** Clears the 'id' field, the 'has' method for this field will now return false */
  public void clearId() {
    genClient.clear(CacheKey.id);
  }
  /** Clears the 'summaryObject' field, the 'has' method for this field will now return false */
  public void clearSummaryObject() {
    genClient.clear(CacheKey.summaryObject);
  }
  /** Clears the 'paymentsSummary' field, the 'has' method for this field will now return false */
  public void clearPaymentsSummary() {
    genClient.clear(CacheKey.paymentsSummary);
  }
  /** Clears the 'refundsSummary' field, the 'has' method for this field will now return false */
  public void clearRefundsSummary() {
    genClient.clear(CacheKey.refundsSummary);
  }
  /** Clears the 'creditsSummary' field, the 'has' method for this field will now return false */
  public void clearCreditsSummary() {
    genClient.clear(CacheKey.creditsSummary);
  }
  /** Clears the 'discountsSummary' field, the 'has' method for this field will now return false */
  public void clearDiscountsSummary() {
    genClient.clear(CacheKey.discountsSummary);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public SummaryGroup copyChanges() {
    SummaryGroup copy = new SummaryGroup();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(SummaryGroup src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new SummaryGroup(src).getJSONObject(), src.genClient);
    }
  }

  public static final android.os.Parcelable.Creator<SummaryGroup> CREATOR = new android.os.Parcelable.Creator<SummaryGroup>() {
    @Override
    public SummaryGroup createFromParcel(android.os.Parcel in) {
      SummaryGroup instance = new SummaryGroup(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public SummaryGroup[] newArray(int size) {
      return new SummaryGroup[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<SummaryGroup> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<SummaryGroup>() {
    public Class<SummaryGroup> getCreatedClass() {
      return SummaryGroup.class;
    }

    @Override
    public SummaryGroup create(org.json.JSONObject jsonObject) {
      return new SummaryGroup(jsonObject);
    }
  };

  public interface Constraints {
    public static final boolean ID_IS_REQUIRED = false;
    public static final boolean SUMMARYOBJECT_IS_REQUIRED = false;
    public static final boolean PAYMENTSSUMMARY_IS_REQUIRED = false;
    public static final boolean REFUNDSSUMMARY_IS_REQUIRED = false;
    public static final boolean CREDITSSUMMARY_IS_REQUIRED = false;
    public static final boolean DISCOUNTSSUMMARY_IS_REQUIRED = false;
  }

}
