/**
 * Copyright (C) 2015 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

package com.clover.sdk.v3.configurator;

import com.clover.sdk.GenericClient;

@SuppressWarnings("all")
public final class AppAndSubscription implements android.os.Parcelable, com.clover.sdk.v3.Validator, com.clover.sdk.JSONifiable {

 /**
  * Unique identifier
  */
  public java.lang.String getId() {
    return genClient.cacheGet(CacheKey.id);
  }
  public com.clover.sdk.v3.apps.AppSubscription getSubscription() {
    return genClient.cacheGet(CacheKey.subscription);
  }
  public com.clover.sdk.v3.apps.App getApp() {
    return genClient.cacheGet(CacheKey.app);
  }


  private enum CacheKey implements com.clover.sdk.ValueExtractorEnum<AppAndSubscription> {
    id {
      @Override
      public Object extractValue(AppAndSubscription instance) {
        return instance.genClient.extractOther("id", java.lang.String.class);
      }
    },
    subscription {
      @Override
      public Object extractValue(AppAndSubscription instance) {
        return instance.genClient.extractRecord("subscription", com.clover.sdk.v3.apps.AppSubscription.JSON_CREATOR);
      }
    },
    app {
      @Override
      public Object extractValue(AppAndSubscription instance) {
        return instance.genClient.extractRecord("app", com.clover.sdk.v3.apps.App.JSON_CREATOR);
      }
    },
    ;
  }

  private GenericClient<AppAndSubscription> genClient = new GenericClient<AppAndSubscription>(this);

  /**
   * Constructs a new empty instance.
   */
  public AppAndSubscription() { }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public AppAndSubscription(String json) throws IllegalArgumentException {
    try {
      genClient.setJsonObject(new org.json.JSONObject(json));
    } catch (org.json.JSONException e) {
      throw new IllegalArgumentException("invalid json", e);
    }
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public AppAndSubscription(org.json.JSONObject jsonObject) {
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public AppAndSubscription(AppAndSubscription src) {
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }


  @Override
  public void validate() {
    genClient.validateLength(getId(), 13);
  }

  /** Checks whether the 'id' field is set and is not null */
  public boolean isNotNullId() {
    return genClient.cacheValueIsNotNull(CacheKey.id);
  }

  /** Checks whether the 'subscription' field is set and is not null */
  public boolean isNotNullSubscription() {
    return genClient.cacheValueIsNotNull(CacheKey.subscription);
  }

  /** Checks whether the 'app' field is set and is not null */
  public boolean isNotNullApp() {
    return genClient.cacheValueIsNotNull(CacheKey.app);
  }


  /** Checks whether the 'id' field has been set, however the value could be null */
  public boolean hasId() {
    return genClient.cacheHasKey(CacheKey.id);
  }

  /** Checks whether the 'subscription' field has been set, however the value could be null */
  public boolean hasSubscription() {
    return genClient.cacheHasKey(CacheKey.subscription);
  }

  /** Checks whether the 'app' field has been set, however the value could be null */
  public boolean hasApp() {
    return genClient.cacheHasKey(CacheKey.app);
  }


  /**
   * Sets the field 'id'.
   */
  public AppAndSubscription setId(java.lang.String id) {
    return genClient.setOther(id, CacheKey.id);
  }

  /**
   * Sets the field 'subscription'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public AppAndSubscription setSubscription(com.clover.sdk.v3.apps.AppSubscription subscription) {
    return genClient.setRecord(subscription, CacheKey.subscription);
  }

  /**
   * Sets the field 'app'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public AppAndSubscription setApp(com.clover.sdk.v3.apps.App app) {
    return genClient.setRecord(app, CacheKey.app);
  }


  /** Clears the 'id' field, the 'has' method for this field will now return false */
  public void clearId() {
    genClient.clear(CacheKey.id);
  }
  /** Clears the 'subscription' field, the 'has' method for this field will now return false */
  public void clearSubscription() {
    genClient.clear(CacheKey.subscription);
  }
  /** Clears the 'app' field, the 'has' method for this field will now return false */
  public void clearApp() {
    genClient.clear(CacheKey.app);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public AppAndSubscription copyChanges() {
    AppAndSubscription copy = new AppAndSubscription();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(AppAndSubscription src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new AppAndSubscription(src).getJSONObject(), src.genClient);
    }
  }

  /**
   * Gets a Bundle which can be used to get and set data attached to this instance. The attached Bundle will be
   * parcelled but not jsonified.
   */
  public android.os.Bundle getBundle() {
    return genClient.getBundle();
  }

  @Override
  public String toString() {
    return genClient.toString();
  }

  @Override
  public int describeContents() {
    return 0;
  }

  @Override
  public void writeToParcel(android.os.Parcel dest, int flags) {
    genClient.writeToParcel(dest, flags);
  }

  public static final android.os.Parcelable.Creator<AppAndSubscription> CREATOR = new android.os.Parcelable.Creator<AppAndSubscription>() {
    @Override
    public AppAndSubscription createFromParcel(android.os.Parcel in) {
      AppAndSubscription instance = new AppAndSubscription(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public AppAndSubscription[] newArray(int size) {
      return new AppAndSubscription[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<AppAndSubscription> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<AppAndSubscription>() {
    @Override
    public AppAndSubscription create(org.json.JSONObject jsonObject) {
      return new AppAndSubscription(jsonObject);
    }
  };


  public interface Constraints {

    public static final boolean ID_IS_REQUIRED = false;
    public static final long ID_MAX_LEN = 13;

    public static final boolean SUBSCRIPTION_IS_REQUIRED = false;

    public static final boolean APP_IS_REQUIRED = false;

  }

}
