/**
 * Copyright (C) 2015 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

package com.clover.sdk.v3.hours;

import com.clover.sdk.GenericClient;

@SuppressWarnings("all")
public final class HourRange implements android.os.Parcelable, com.clover.sdk.v3.Validator, com.clover.sdk.JSONifiable {

  public java.lang.Integer getStart() {
    return genClient.cacheGet(CacheKey.start);
  }
  public java.lang.Integer getEnd() {
    return genClient.cacheGet(CacheKey.end);
  }


  private enum CacheKey implements com.clover.sdk.ValueExtractorEnum<HourRange> {
    start {
      @Override
      public Object extractValue(HourRange instance) {
        return instance.genClient.extractOther("start", java.lang.Integer.class);
      }
    },
    end {
      @Override
      public Object extractValue(HourRange instance) {
        return instance.genClient.extractOther("end", java.lang.Integer.class);
      }
    },
    ;
  }

  private GenericClient<HourRange> genClient = new GenericClient<HourRange>(this);

  /**
   * Constructs a new empty instance.
   */
  public HourRange() { }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public HourRange(String json) throws IllegalArgumentException {
    try {
      genClient.setJsonObject(new org.json.JSONObject(json));
    } catch (org.json.JSONException e) {
      throw new IllegalArgumentException("invalid json", e);
    }
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public HourRange(org.json.JSONObject jsonObject) {
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public HourRange(HourRange src) {
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }


  @Override
  public void validate() {
    genClient.validateNull(getStart(), "start");

    genClient.validateNull(getEnd(), "end");
  }

  /** Checks whether the 'start' field is set and is not null */
  public boolean isNotNullStart() {
    return genClient.cacheValueIsNotNull(CacheKey.start);
  }

  /** Checks whether the 'end' field is set and is not null */
  public boolean isNotNullEnd() {
    return genClient.cacheValueIsNotNull(CacheKey.end);
  }


  /** Checks whether the 'start' field has been set, however the value could be null */
  public boolean hasStart() {
    return genClient.cacheHasKey(CacheKey.start);
  }

  /** Checks whether the 'end' field has been set, however the value could be null */
  public boolean hasEnd() {
    return genClient.cacheHasKey(CacheKey.end);
  }


  /**
   * Sets the field 'start'.
   */
  public HourRange setStart(java.lang.Integer start) {
    return genClient.setOther(start, CacheKey.start);
  }

  /**
   * Sets the field 'end'.
   */
  public HourRange setEnd(java.lang.Integer end) {
    return genClient.setOther(end, CacheKey.end);
  }


  /** Clears the 'start' field, the 'has' method for this field will now return false */
  public void clearStart() {
    genClient.clear(CacheKey.start);
  }
  /** Clears the 'end' field, the 'has' method for this field will now return false */
  public void clearEnd() {
    genClient.clear(CacheKey.end);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public HourRange copyChanges() {
    HourRange copy = new HourRange();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(HourRange src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new HourRange(src).getJSONObject(), src.genClient);
    }
  }

  /**
   * Gets a Bundle which can be used to get and set data attached to this instance. The attached Bundle will be
   * parcelled but not jsonified.
   */
  public android.os.Bundle getBundle() {
    return genClient.getBundle();
  }

  @Override
  public String toString() {
    return genClient.toString();
  }

  @Override
  public int describeContents() {
    return 0;
  }

  @Override
  public void writeToParcel(android.os.Parcel dest, int flags) {
    genClient.writeToParcel(dest, flags);
  }

  public static final android.os.Parcelable.Creator<HourRange> CREATOR = new android.os.Parcelable.Creator<HourRange>() {
    @Override
    public HourRange createFromParcel(android.os.Parcel in) {
      HourRange instance = new HourRange(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public HourRange[] newArray(int size) {
      return new HourRange[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<HourRange> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<HourRange>() {
    @Override
    public HourRange create(org.json.JSONObject jsonObject) {
      return new HourRange(jsonObject);
    }
  };


  public interface Constraints {

    public static final boolean START_IS_REQUIRED = true;

    public static final boolean END_IS_REQUIRED = true;

  }

}
