/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/*
 * Copyright (C) 2019 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.sdk.v3.remotepay;

import com.clover.sdk.GenericClient;

/**
 * This is an auto-generated Clover data object.
 * <p>
 * <h3>Fields</h3>
 * <ul>
 * <li>{@link #getTipAmount tipAmount}</li>
 * <li>{@link #getTipMode tipMode}</li>
 * </ul>
 */
@SuppressWarnings("all")
public class SaleRequest extends com.clover.sdk.v3.remotepay.TransactionRequest {

  /**
   * Included tip
   */
  public java.lang.Long getTipAmount() {
    return genClient.cacheGet(CacheKey.tipAmount);
  }

  public com.clover.sdk.v3.payments.TipMode getTipMode() {
    return genClient.cacheGet(CacheKey.tipMode);
  }

  /**
   * If the amount is equal to or greater than this amount, then a signature should be obtained
   */
  @Override
  public java.lang.Long getSignatureThreshold() {
    return genClient.cacheGet(CacheKey.signatureThreshold);
  }

  /**
   * Where the signature should be obtained from (paper, screen...etc)
   */
  @Override
  public com.clover.sdk.v3.payments.DataEntryLocation getSignatureEntryLocation() {
    return genClient.cacheGet(CacheKey.signatureEntryLocation);
  }

  /**
   * Do not show/send signature verification challenges
   */
  @Override
  public java.lang.Boolean getAutoAcceptSignature() {
    return genClient.cacheGet(CacheKey.autoAcceptSignature);
  }

  /**
   * If true then offline payments can be accepted
   */
  @Override
  public java.lang.Boolean getAllowOfflinePayment() {
    return genClient.cacheGet(CacheKey.allowOfflinePayment);
  }

  /**
   * If true then the payment will be taken offline
   */
  @Override
  public java.lang.Boolean getForceOfflinePayment() {
    return genClient.cacheGet(CacheKey.forceOfflinePayment);
  }

  /**
   * If true, do not allow cash back
   */
  @Override
  public java.lang.Boolean getDisableCashback() {
    return genClient.cacheGet(CacheKey.disableCashback);
  }

  /**
   * If true then offline payments will be approved without a prompt
   */
  @Override
  public java.lang.Boolean getApproveOfflinePaymentWithoutPrompt() {
    return genClient.cacheGet(CacheKey.approveOfflinePaymentWithoutPrompt);
  }

  /**
   * Amount paid in taxes
   */
  @Override
  public java.lang.Long getTaxAmount() {
    return genClient.cacheGet(CacheKey.taxAmount);
  }

  /**
   * The total amount used when calculating tips
   */
  @Override
  public java.lang.Long getTippableAmount() {
    return genClient.cacheGet(CacheKey.tippableAmount);
  }

  /**
   * Custom Tip Suggestions that can be set per transaction
   */
  @Override
  public java.util.List<com.clover.sdk.v3.merchant.TipSuggestion> getTipSuggestions() {
    return genClient.cacheGet(CacheKey.tipSuggestions);
  }

  /**
   * Identifier for the order to apply this to. The order must exist in the clover system.  **NOTE**  THIS FIELD IS ONLY USED BY THE PAYMENT CONNECTOR. It provides functionality currently available to the native PayIntent but not supported yet by the remote pay SDKs
   */
  @Override
  public java.lang.String getOrderId() {
    return genClient.cacheGet(CacheKey.orderId);
  }

  /**
   * If true, then do not print using the clover printer.  Return print information.
   */
  @Override
  public java.lang.Boolean getDisablePrinting() {
    return genClient.cacheGet(CacheKey.disablePrinting);
  }

  /**
   * Do not show the receipt options screen
   */
  @Override
  public java.lang.Boolean getDisableReceiptSelection() {
    return genClient.cacheGet(CacheKey.disableReceiptSelection);
  }

  /**
   * Do not do heuristic duplicate checking
   */
  @Override
  public java.lang.Boolean getDisableDuplicateChecking() {
    return genClient.cacheGet(CacheKey.disableDuplicateChecking);
  }

  /**
   * If true then card not present is accepted
   */
  @Override
  public java.lang.Boolean getCardNotPresent() {
    return genClient.cacheGet(CacheKey.cardNotPresent);
  }

  /**
   * If the transaction times out or fails because of decline, do not restart it
   */
  @Override
  public java.lang.Boolean getDisableRestartTransactionOnFail() {
    return genClient.cacheGet(CacheKey.disableRestartTransactionOnFail);
  }

  /**
   * Total amount paid
   */
  @Override
  public java.lang.Long getAmount() {
    return genClient.cacheGet(CacheKey.amount);
  }

  /**
   * Allowed entry methods
   */
  @Override
  public java.lang.Integer getCardEntryMethods() {
    return genClient.cacheGet(CacheKey.cardEntryMethods);
  }

  /**
   * A saved card
   */
  @Override
  public com.clover.sdk.v3.payments.VaultedCard getVaultedCard() {
    return genClient.cacheGet(CacheKey.vaultedCard);
  }

  /**
   * An id that will be persisted with transactions.
   */
  @Override
  public java.lang.String getExternalId() {
    return genClient.cacheGet(CacheKey.externalId);
  }

  /**
   * The type of the transaction.
   */
  @Override
  public com.clover.sdk.v3.remotepay.TransactionType getType() {
    return genClient.cacheGet(CacheKey.type);
  }

  /**
   * Do not show/send potential duplicate challenges
   */
  @Override
  public java.lang.Boolean getAutoAcceptPaymentConfirmations() {
    return genClient.cacheGet(CacheKey.autoAcceptPaymentConfirmations);
  }

  /**
   * Extra pass-through data used by external systems.
   */
  @Override
  public java.util.Map<java.lang.String,java.lang.String> getExtras() {
    return genClient.cacheGet(CacheKey.extras);
  }

  /**
   * A map of values for regional specific data
   */
  @Override
  public java.util.Map<java.lang.String,java.lang.String> getRegionalExtras() {
    return genClient.cacheGet(CacheKey.regionalExtras);
  }

  /**
   * An id that can be passed to the merchant's gateway, and ultimately appear in settlement records.
   */
  @Override
  public java.lang.String getExternalReferenceId() {
    return genClient.cacheGet(CacheKey.externalReferenceId);
  }

  /**
   * Identifier for the request
   */
  @Override
  public java.lang.String getRequestId() {
    return genClient.cacheGet(CacheKey.requestId);
  }

  /**
   * Identifier for the version
   */
  @Override
  public java.lang.Integer getVersion() {
    return genClient.cacheGet(CacheKey.version);
  }




  private enum CacheKey implements com.clover.sdk.ExtractionStrategyEnum {
    tipAmount
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Long.class)),
    tipMode
        (com.clover.sdk.extractors.EnumExtractionStrategy.instance(com.clover.sdk.v3.payments.TipMode.class)),
    signatureThreshold
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Long.class)),
    signatureEntryLocation
        (com.clover.sdk.extractors.EnumExtractionStrategy.instance(com.clover.sdk.v3.payments.DataEntryLocation.class)),
    autoAcceptSignature
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    allowOfflinePayment
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    forceOfflinePayment
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    disableCashback
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    approveOfflinePaymentWithoutPrompt
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    taxAmount
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Long.class)),
    tippableAmount
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Long.class)),
    tipSuggestions
        (com.clover.sdk.extractors.RecordListExtractionStrategy.instance(com.clover.sdk.v3.merchant.TipSuggestion.JSON_CREATOR)),
    orderId
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.String.class)),
    disablePrinting
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    disableReceiptSelection
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    disableDuplicateChecking
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    cardNotPresent
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    disableRestartTransactionOnFail
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    amount
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Long.class)),
    cardEntryMethods
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Integer.class)),
    vaultedCard
        (com.clover.sdk.extractors.RecordExtractionStrategy.instance(com.clover.sdk.v3.payments.VaultedCard.JSON_CREATOR)),
    externalId
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.String.class)),
    type
        (com.clover.sdk.extractors.EnumExtractionStrategy.instance(com.clover.sdk.v3.remotepay.TransactionType.class)),
    autoAcceptPaymentConfirmations
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Boolean.class)),
    extras
        (com.clover.sdk.extractors.MapExtractionStrategy.instance()),
    regionalExtras
        (com.clover.sdk.extractors.MapExtractionStrategy.instance()),
    externalReferenceId
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.String.class)),
    requestId
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.String.class)),
    version
        (com.clover.sdk.extractors.BasicExtractionStrategy.instance(java.lang.Integer.class)),
      ;

    private final com.clover.sdk.extractors.ExtractionStrategy extractionStrategy;

    private CacheKey(com.clover.sdk.extractors.ExtractionStrategy s) {
      extractionStrategy = s;
    }

    @Override
    public com.clover.sdk.extractors.ExtractionStrategy getExtractionStrategy() {
      return extractionStrategy;
    }
  }

  private final GenericClient<SaleRequest> genClient;

  /**
   * Constructs a new empty instance.
   */
  public SaleRequest() {
    super(false);
    genClient = new GenericClient<SaleRequest>(this);
    this.setType(com.clover.sdk.v3.remotepay.TransactionType.PAYMENT);
  }

  @Override
  protected GenericClient getGenericClient() {
    return genClient;
  }

  /**
   * Constructs a new empty instance.
   */
  protected SaleRequest(boolean noInit) {
    super(false);
    genClient = null;
  }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public SaleRequest(String json) throws IllegalArgumentException {
    this();
    try {
      genClient.setJsonObject(new org.json.JSONObject(json));
    } catch (org.json.JSONException e) {
      throw new IllegalArgumentException("invalid json", e);
    }
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public SaleRequest(org.json.JSONObject jsonObject) {
    this();
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public SaleRequest(SaleRequest src) {
    this();
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }

  @Override
  public void validate() {

    genClient.validateLength(getOrderId(), 13);

    genClient.validateNull(getAmount(), "amount");

    genClient.validateNull(getExternalId(), "externalId");
    genClient.validateLength(getRequestId(), 13);
  }

  /** Checks whether the 'tipAmount' field is set and is not null */
  public boolean isNotNullTipAmount() {
    return genClient.cacheValueIsNotNull(CacheKey.tipAmount);
  }

  /** Checks whether the 'tipMode' field is set and is not null */
  public boolean isNotNullTipMode() {
    return genClient.cacheValueIsNotNull(CacheKey.tipMode);
  }

  /** Checks whether the 'signatureThreshold' field is set and is not null */
  @Override
  public boolean isNotNullSignatureThreshold() {
    return genClient.cacheValueIsNotNull(CacheKey.signatureThreshold);
  }

  /** Checks whether the 'signatureEntryLocation' field is set and is not null */
  @Override
  public boolean isNotNullSignatureEntryLocation() {
    return genClient.cacheValueIsNotNull(CacheKey.signatureEntryLocation);
  }

  /** Checks whether the 'autoAcceptSignature' field is set and is not null */
  @Override
  public boolean isNotNullAutoAcceptSignature() {
    return genClient.cacheValueIsNotNull(CacheKey.autoAcceptSignature);
  }

  /** Checks whether the 'allowOfflinePayment' field is set and is not null */
  @Override
  public boolean isNotNullAllowOfflinePayment() {
    return genClient.cacheValueIsNotNull(CacheKey.allowOfflinePayment);
  }

  /** Checks whether the 'forceOfflinePayment' field is set and is not null */
  @Override
  public boolean isNotNullForceOfflinePayment() {
    return genClient.cacheValueIsNotNull(CacheKey.forceOfflinePayment);
  }

  /** Checks whether the 'disableCashback' field is set and is not null */
  @Override
  public boolean isNotNullDisableCashback() {
    return genClient.cacheValueIsNotNull(CacheKey.disableCashback);
  }

  /** Checks whether the 'approveOfflinePaymentWithoutPrompt' field is set and is not null */
  @Override
  public boolean isNotNullApproveOfflinePaymentWithoutPrompt() {
    return genClient.cacheValueIsNotNull(CacheKey.approveOfflinePaymentWithoutPrompt);
  }

  /** Checks whether the 'taxAmount' field is set and is not null */
  @Override
  public boolean isNotNullTaxAmount() {
    return genClient.cacheValueIsNotNull(CacheKey.taxAmount);
  }

  /** Checks whether the 'tippableAmount' field is set and is not null */
  @Override
  public boolean isNotNullTippableAmount() {
    return genClient.cacheValueIsNotNull(CacheKey.tippableAmount);
  }

  /** Checks whether the 'tipSuggestions' field is set and is not null */
  @Override
  public boolean isNotNullTipSuggestions() {
    return genClient.cacheValueIsNotNull(CacheKey.tipSuggestions);
  }

  /** Checks whether the 'tipSuggestions' field is set and is not null and is not empty */
  public boolean isNotEmptyTipSuggestions() { return isNotNullTipSuggestions() && !getTipSuggestions().isEmpty(); }

  /** Checks whether the 'orderId' field is set and is not null */
  @Override
  public boolean isNotNullOrderId() {
    return genClient.cacheValueIsNotNull(CacheKey.orderId);
  }

  /** Checks whether the 'disablePrinting' field is set and is not null */
  @Override
  public boolean isNotNullDisablePrinting() {
    return genClient.cacheValueIsNotNull(CacheKey.disablePrinting);
  }

  /** Checks whether the 'disableReceiptSelection' field is set and is not null */
  @Override
  public boolean isNotNullDisableReceiptSelection() {
    return genClient.cacheValueIsNotNull(CacheKey.disableReceiptSelection);
  }

  /** Checks whether the 'disableDuplicateChecking' field is set and is not null */
  @Override
  public boolean isNotNullDisableDuplicateChecking() {
    return genClient.cacheValueIsNotNull(CacheKey.disableDuplicateChecking);
  }

  /** Checks whether the 'cardNotPresent' field is set and is not null */
  @Override
  public boolean isNotNullCardNotPresent() {
    return genClient.cacheValueIsNotNull(CacheKey.cardNotPresent);
  }

  /** Checks whether the 'disableRestartTransactionOnFail' field is set and is not null */
  @Override
  public boolean isNotNullDisableRestartTransactionOnFail() {
    return genClient.cacheValueIsNotNull(CacheKey.disableRestartTransactionOnFail);
  }

  /** Checks whether the 'amount' field is set and is not null */
  @Override
  public boolean isNotNullAmount() {
    return genClient.cacheValueIsNotNull(CacheKey.amount);
  }

  /** Checks whether the 'cardEntryMethods' field is set and is not null */
  @Override
  public boolean isNotNullCardEntryMethods() {
    return genClient.cacheValueIsNotNull(CacheKey.cardEntryMethods);
  }

  /** Checks whether the 'vaultedCard' field is set and is not null */
  @Override
  public boolean isNotNullVaultedCard() {
    return genClient.cacheValueIsNotNull(CacheKey.vaultedCard);
  }

  /** Checks whether the 'externalId' field is set and is not null */
  @Override
  public boolean isNotNullExternalId() {
    return genClient.cacheValueIsNotNull(CacheKey.externalId);
  }

  /** Checks whether the 'type' field is set and is not null */
  @Override
  public boolean isNotNullType() {
    return genClient.cacheValueIsNotNull(CacheKey.type);
  }

  /** Checks whether the 'autoAcceptPaymentConfirmations' field is set and is not null */
  @Override
  public boolean isNotNullAutoAcceptPaymentConfirmations() {
    return genClient.cacheValueIsNotNull(CacheKey.autoAcceptPaymentConfirmations);
  }

  /** Checks whether the 'extras' field is set and is not null */
  @Override
  public boolean isNotNullExtras() {
    return genClient.cacheValueIsNotNull(CacheKey.extras);
  }

  /** Checks whether the 'extras' field is set and is not null and is not empty */
  public boolean isNotEmptyExtras() { return isNotNullExtras() && !getExtras().isEmpty(); }

  /** Checks whether the 'regionalExtras' field is set and is not null */
  @Override
  public boolean isNotNullRegionalExtras() {
    return genClient.cacheValueIsNotNull(CacheKey.regionalExtras);
  }

  /** Checks whether the 'regionalExtras' field is set and is not null and is not empty */
  public boolean isNotEmptyRegionalExtras() { return isNotNullRegionalExtras() && !getRegionalExtras().isEmpty(); }

  /** Checks whether the 'externalReferenceId' field is set and is not null */
  @Override
  public boolean isNotNullExternalReferenceId() {
    return genClient.cacheValueIsNotNull(CacheKey.externalReferenceId);
  }

  /** Checks whether the 'requestId' field is set and is not null */
  @Override
  public boolean isNotNullRequestId() {
    return genClient.cacheValueIsNotNull(CacheKey.requestId);
  }

  /** Checks whether the 'version' field is set and is not null */
  @Override
  public boolean isNotNullVersion() {
    return genClient.cacheValueIsNotNull(CacheKey.version);
  }



  /** Checks whether the 'tipAmount' field has been set, however the value could be null */
  public boolean hasTipAmount() {
    return genClient.cacheHasKey(CacheKey.tipAmount);
  }

  /** Checks whether the 'tipMode' field has been set, however the value could be null */
  public boolean hasTipMode() {
    return genClient.cacheHasKey(CacheKey.tipMode);
  }

  /** Checks whether the 'signatureThreshold' field has been set, however the value could be null */
  @Override
  public boolean hasSignatureThreshold() {
    return genClient.cacheHasKey(CacheKey.signatureThreshold);
  }

  /** Checks whether the 'signatureEntryLocation' field has been set, however the value could be null */
  @Override
  public boolean hasSignatureEntryLocation() {
    return genClient.cacheHasKey(CacheKey.signatureEntryLocation);
  }

  /** Checks whether the 'autoAcceptSignature' field has been set, however the value could be null */
  @Override
  public boolean hasAutoAcceptSignature() {
    return genClient.cacheHasKey(CacheKey.autoAcceptSignature);
  }

  /** Checks whether the 'allowOfflinePayment' field has been set, however the value could be null */
  @Override
  public boolean hasAllowOfflinePayment() {
    return genClient.cacheHasKey(CacheKey.allowOfflinePayment);
  }

  /** Checks whether the 'forceOfflinePayment' field has been set, however the value could be null */
  @Override
  public boolean hasForceOfflinePayment() {
    return genClient.cacheHasKey(CacheKey.forceOfflinePayment);
  }

  /** Checks whether the 'disableCashback' field has been set, however the value could be null */
  @Override
  public boolean hasDisableCashback() {
    return genClient.cacheHasKey(CacheKey.disableCashback);
  }

  /** Checks whether the 'approveOfflinePaymentWithoutPrompt' field has been set, however the value could be null */
  @Override
  public boolean hasApproveOfflinePaymentWithoutPrompt() {
    return genClient.cacheHasKey(CacheKey.approveOfflinePaymentWithoutPrompt);
  }

  /** Checks whether the 'taxAmount' field has been set, however the value could be null */
  @Override
  public boolean hasTaxAmount() {
    return genClient.cacheHasKey(CacheKey.taxAmount);
  }

  /** Checks whether the 'tippableAmount' field has been set, however the value could be null */
  @Override
  public boolean hasTippableAmount() {
    return genClient.cacheHasKey(CacheKey.tippableAmount);
  }

  /** Checks whether the 'tipSuggestions' field has been set, however the value could be null */
  @Override
  public boolean hasTipSuggestions() {
    return genClient.cacheHasKey(CacheKey.tipSuggestions);
  }

  /** Checks whether the 'orderId' field has been set, however the value could be null */
  @Override
  public boolean hasOrderId() {
    return genClient.cacheHasKey(CacheKey.orderId);
  }

  /** Checks whether the 'disablePrinting' field has been set, however the value could be null */
  @Override
  public boolean hasDisablePrinting() {
    return genClient.cacheHasKey(CacheKey.disablePrinting);
  }

  /** Checks whether the 'disableReceiptSelection' field has been set, however the value could be null */
  @Override
  public boolean hasDisableReceiptSelection() {
    return genClient.cacheHasKey(CacheKey.disableReceiptSelection);
  }

  /** Checks whether the 'disableDuplicateChecking' field has been set, however the value could be null */
  @Override
  public boolean hasDisableDuplicateChecking() {
    return genClient.cacheHasKey(CacheKey.disableDuplicateChecking);
  }

  /** Checks whether the 'cardNotPresent' field has been set, however the value could be null */
  @Override
  public boolean hasCardNotPresent() {
    return genClient.cacheHasKey(CacheKey.cardNotPresent);
  }

  /** Checks whether the 'disableRestartTransactionOnFail' field has been set, however the value could be null */
  @Override
  public boolean hasDisableRestartTransactionOnFail() {
    return genClient.cacheHasKey(CacheKey.disableRestartTransactionOnFail);
  }

  /** Checks whether the 'amount' field has been set, however the value could be null */
  @Override
  public boolean hasAmount() {
    return genClient.cacheHasKey(CacheKey.amount);
  }

  /** Checks whether the 'cardEntryMethods' field has been set, however the value could be null */
  @Override
  public boolean hasCardEntryMethods() {
    return genClient.cacheHasKey(CacheKey.cardEntryMethods);
  }

  /** Checks whether the 'vaultedCard' field has been set, however the value could be null */
  @Override
  public boolean hasVaultedCard() {
    return genClient.cacheHasKey(CacheKey.vaultedCard);
  }

  /** Checks whether the 'externalId' field has been set, however the value could be null */
  @Override
  public boolean hasExternalId() {
    return genClient.cacheHasKey(CacheKey.externalId);
  }

  /** Checks whether the 'type' field has been set, however the value could be null */
  @Override
  public boolean hasType() {
    return genClient.cacheHasKey(CacheKey.type);
  }

  /** Checks whether the 'autoAcceptPaymentConfirmations' field has been set, however the value could be null */
  @Override
  public boolean hasAutoAcceptPaymentConfirmations() {
    return genClient.cacheHasKey(CacheKey.autoAcceptPaymentConfirmations);
  }

  /** Checks whether the 'extras' field has been set, however the value could be null */
  @Override
  public boolean hasExtras() {
    return genClient.cacheHasKey(CacheKey.extras);
  }

  /** Checks whether the 'regionalExtras' field has been set, however the value could be null */
  @Override
  public boolean hasRegionalExtras() {
    return genClient.cacheHasKey(CacheKey.regionalExtras);
  }

  /** Checks whether the 'externalReferenceId' field has been set, however the value could be null */
  @Override
  public boolean hasExternalReferenceId() {
    return genClient.cacheHasKey(CacheKey.externalReferenceId);
  }

  /** Checks whether the 'requestId' field has been set, however the value could be null */
  @Override
  public boolean hasRequestId() {
    return genClient.cacheHasKey(CacheKey.requestId);
  }

  /** Checks whether the 'version' field has been set, however the value could be null */
  @Override
  public boolean hasVersion() {
    return genClient.cacheHasKey(CacheKey.version);
  }


  /**
   * Sets the field 'tipAmount'.
   */
  public SaleRequest setTipAmount(java.lang.Long tipAmount) {
    return genClient.setOther(tipAmount, CacheKey.tipAmount);
  }

  /**
   * Sets the field 'tipMode'.
   */
  public SaleRequest setTipMode(com.clover.sdk.v3.payments.TipMode tipMode) {
    return genClient.setOther(tipMode, CacheKey.tipMode);
  }

  /**
   * Sets the field 'signatureThreshold'.
   */
  @Override
  public TransactionRequest setSignatureThreshold(java.lang.Long signatureThreshold) {
    return genClient.setOther(signatureThreshold, CacheKey.signatureThreshold);
  }

  /**
   * Sets the field 'signatureEntryLocation'.
   */
  @Override
  public TransactionRequest setSignatureEntryLocation(com.clover.sdk.v3.payments.DataEntryLocation signatureEntryLocation) {
    return genClient.setOther(signatureEntryLocation, CacheKey.signatureEntryLocation);
  }

  /**
   * Sets the field 'autoAcceptSignature'.
   */
  @Override
  public TransactionRequest setAutoAcceptSignature(java.lang.Boolean autoAcceptSignature) {
    return genClient.setOther(autoAcceptSignature, CacheKey.autoAcceptSignature);
  }

  /**
   * Sets the field 'allowOfflinePayment'.
   */
  @Override
  public TransactionRequest setAllowOfflinePayment(java.lang.Boolean allowOfflinePayment) {
    return genClient.setOther(allowOfflinePayment, CacheKey.allowOfflinePayment);
  }

  /**
   * Sets the field 'forceOfflinePayment'.
   */
  @Override
  public TransactionRequest setForceOfflinePayment(java.lang.Boolean forceOfflinePayment) {
    return genClient.setOther(forceOfflinePayment, CacheKey.forceOfflinePayment);
  }

  /**
   * Sets the field 'disableCashback'.
   */
  @Override
  public TransactionRequest setDisableCashback(java.lang.Boolean disableCashback) {
    return genClient.setOther(disableCashback, CacheKey.disableCashback);
  }

  /**
   * Sets the field 'approveOfflinePaymentWithoutPrompt'.
   */
  @Override
  public TransactionRequest setApproveOfflinePaymentWithoutPrompt(java.lang.Boolean approveOfflinePaymentWithoutPrompt) {
    return genClient.setOther(approveOfflinePaymentWithoutPrompt, CacheKey.approveOfflinePaymentWithoutPrompt);
  }

  /**
   * Sets the field 'taxAmount'.
   */
  @Override
  public TransactionRequest setTaxAmount(java.lang.Long taxAmount) {
    return genClient.setOther(taxAmount, CacheKey.taxAmount);
  }

  /**
   * Sets the field 'tippableAmount'.
   */
  @Override
  public TransactionRequest setTippableAmount(java.lang.Long tippableAmount) {
    return genClient.setOther(tippableAmount, CacheKey.tippableAmount);
  }

  /**
   * Sets the field 'tipSuggestions'.
   *
   * Nulls in the given List are skipped. List parameter is copied, so it will not reflect any changes, but objects inside it will.
   */
  @Override
  public TransactionRequest setTipSuggestions(java.util.List<com.clover.sdk.v3.merchant.TipSuggestion> tipSuggestions) {
    return genClient.setArrayRecord(tipSuggestions, CacheKey.tipSuggestions);
  }

  /**
   * Sets the field 'orderId'.
   */
  @Override
  public BaseTransactionRequest setOrderId(java.lang.String orderId) {
    return genClient.setOther(orderId, CacheKey.orderId);
  }

  /**
   * Sets the field 'disablePrinting'.
   */
  @Override
  public BaseTransactionRequest setDisablePrinting(java.lang.Boolean disablePrinting) {
    return genClient.setOther(disablePrinting, CacheKey.disablePrinting);
  }

  /**
   * Sets the field 'disableReceiptSelection'.
   */
  @Override
  public BaseTransactionRequest setDisableReceiptSelection(java.lang.Boolean disableReceiptSelection) {
    return genClient.setOther(disableReceiptSelection, CacheKey.disableReceiptSelection);
  }

  /**
   * Sets the field 'disableDuplicateChecking'.
   */
  @Override
  public BaseTransactionRequest setDisableDuplicateChecking(java.lang.Boolean disableDuplicateChecking) {
    return genClient.setOther(disableDuplicateChecking, CacheKey.disableDuplicateChecking);
  }

  /**
   * Sets the field 'cardNotPresent'.
   */
  @Override
  public BaseTransactionRequest setCardNotPresent(java.lang.Boolean cardNotPresent) {
    return genClient.setOther(cardNotPresent, CacheKey.cardNotPresent);
  }

  /**
   * Sets the field 'disableRestartTransactionOnFail'.
   */
  @Override
  public BaseTransactionRequest setDisableRestartTransactionOnFail(java.lang.Boolean disableRestartTransactionOnFail) {
    return genClient.setOther(disableRestartTransactionOnFail, CacheKey.disableRestartTransactionOnFail);
  }

  /**
   * Sets the field 'amount'.
   */
  @Override
  public BaseTransactionRequest setAmount(java.lang.Long amount) {
    return genClient.setOther(amount, CacheKey.amount);
  }

  /**
   * Sets the field 'cardEntryMethods'.
   */
  @Override
  public BaseTransactionRequest setCardEntryMethods(java.lang.Integer cardEntryMethods) {
    return genClient.setOther(cardEntryMethods, CacheKey.cardEntryMethods);
  }

  /**
   * Sets the field 'vaultedCard'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  @Override
  public BaseTransactionRequest setVaultedCard(com.clover.sdk.v3.payments.VaultedCard vaultedCard) {
    return genClient.setRecord(vaultedCard, CacheKey.vaultedCard);
  }

  /**
   * Sets the field 'externalId'.
   */
  @Override
  public BaseTransactionRequest setExternalId(java.lang.String externalId) {
    return genClient.setOther(externalId, CacheKey.externalId);
  }

  /**
   * Sets the field 'type'.
   */
  @Override
  public BaseTransactionRequest setType(com.clover.sdk.v3.remotepay.TransactionType type) {
    return genClient.setOther(type, CacheKey.type);
  }

  /**
   * Sets the field 'autoAcceptPaymentConfirmations'.
   */
  @Override
  public BaseTransactionRequest setAutoAcceptPaymentConfirmations(java.lang.Boolean autoAcceptPaymentConfirmations) {
    return genClient.setOther(autoAcceptPaymentConfirmations, CacheKey.autoAcceptPaymentConfirmations);
  }

  /**
   * Sets the field 'extras'.
   */
  @Override
  public BaseTransactionRequest setExtras(java.util.Map<java.lang.String,java.lang.String> extras) {
    return genClient.setOther(extras, CacheKey.extras);
  }

  /**
   * Sets the field 'regionalExtras'.
   */
  @Override
  public BaseTransactionRequest setRegionalExtras(java.util.Map<java.lang.String,java.lang.String> regionalExtras) {
    return genClient.setOther(regionalExtras, CacheKey.regionalExtras);
  }

  /**
   * Sets the field 'externalReferenceId'.
   */
  @Override
  public BaseTransactionRequest setExternalReferenceId(java.lang.String externalReferenceId) {
    return genClient.setOther(externalReferenceId, CacheKey.externalReferenceId);
  }

  /**
   * Sets the field 'requestId'.
   */
  @Override
  public BaseRequest setRequestId(java.lang.String requestId) {
    return genClient.setOther(requestId, CacheKey.requestId);
  }

  /**
   * Sets the field 'version'.
   */
  @Override
  public BaseRequest setVersion(java.lang.Integer version) {
    return genClient.setOther(version, CacheKey.version);
  }


  /** Clears the 'tipAmount' field, the 'has' method for this field will now return false */
  public void clearTipAmount() {
    genClient.clear(CacheKey.tipAmount);
  }
  /** Clears the 'tipMode' field, the 'has' method for this field will now return false */
  public void clearTipMode() {
    genClient.clear(CacheKey.tipMode);
  }
  /** Clears the 'signatureThreshold' field, the 'has' method for this field will now return false */
  @Override
  public void clearSignatureThreshold() {
    genClient.clear(CacheKey.signatureThreshold);
  }
  /** Clears the 'signatureEntryLocation' field, the 'has' method for this field will now return false */
  @Override
  public void clearSignatureEntryLocation() {
    genClient.clear(CacheKey.signatureEntryLocation);
  }
  /** Clears the 'autoAcceptSignature' field, the 'has' method for this field will now return false */
  @Override
  public void clearAutoAcceptSignature() {
    genClient.clear(CacheKey.autoAcceptSignature);
  }
  /** Clears the 'allowOfflinePayment' field, the 'has' method for this field will now return false */
  @Override
  public void clearAllowOfflinePayment() {
    genClient.clear(CacheKey.allowOfflinePayment);
  }
  /** Clears the 'forceOfflinePayment' field, the 'has' method for this field will now return false */
  @Override
  public void clearForceOfflinePayment() {
    genClient.clear(CacheKey.forceOfflinePayment);
  }
  /** Clears the 'disableCashback' field, the 'has' method for this field will now return false */
  @Override
  public void clearDisableCashback() {
    genClient.clear(CacheKey.disableCashback);
  }
  /** Clears the 'approveOfflinePaymentWithoutPrompt' field, the 'has' method for this field will now return false */
  @Override
  public void clearApproveOfflinePaymentWithoutPrompt() {
    genClient.clear(CacheKey.approveOfflinePaymentWithoutPrompt);
  }
  /** Clears the 'taxAmount' field, the 'has' method for this field will now return false */
  @Override
  public void clearTaxAmount() {
    genClient.clear(CacheKey.taxAmount);
  }
  /** Clears the 'tippableAmount' field, the 'has' method for this field will now return false */
  @Override
  public void clearTippableAmount() {
    genClient.clear(CacheKey.tippableAmount);
  }
  /** Clears the 'tipSuggestions' field, the 'has' method for this field will now return false */
  @Override
  public void clearTipSuggestions() {
    genClient.clear(CacheKey.tipSuggestions);
  }
  /** Clears the 'orderId' field, the 'has' method for this field will now return false */
  @Override
  public void clearOrderId() {
    genClient.clear(CacheKey.orderId);
  }
  /** Clears the 'disablePrinting' field, the 'has' method for this field will now return false */
  @Override
  public void clearDisablePrinting() {
    genClient.clear(CacheKey.disablePrinting);
  }
  /** Clears the 'disableReceiptSelection' field, the 'has' method for this field will now return false */
  @Override
  public void clearDisableReceiptSelection() {
    genClient.clear(CacheKey.disableReceiptSelection);
  }
  /** Clears the 'disableDuplicateChecking' field, the 'has' method for this field will now return false */
  @Override
  public void clearDisableDuplicateChecking() {
    genClient.clear(CacheKey.disableDuplicateChecking);
  }
  /** Clears the 'cardNotPresent' field, the 'has' method for this field will now return false */
  @Override
  public void clearCardNotPresent() {
    genClient.clear(CacheKey.cardNotPresent);
  }
  /** Clears the 'disableRestartTransactionOnFail' field, the 'has' method for this field will now return false */
  @Override
  public void clearDisableRestartTransactionOnFail() {
    genClient.clear(CacheKey.disableRestartTransactionOnFail);
  }
  /** Clears the 'amount' field, the 'has' method for this field will now return false */
  @Override
  public void clearAmount() {
    genClient.clear(CacheKey.amount);
  }
  /** Clears the 'cardEntryMethods' field, the 'has' method for this field will now return false */
  @Override
  public void clearCardEntryMethods() {
    genClient.clear(CacheKey.cardEntryMethods);
  }
  /** Clears the 'vaultedCard' field, the 'has' method for this field will now return false */
  @Override
  public void clearVaultedCard() {
    genClient.clear(CacheKey.vaultedCard);
  }
  /** Clears the 'externalId' field, the 'has' method for this field will now return false */
  @Override
  public void clearExternalId() {
    genClient.clear(CacheKey.externalId);
  }
  /** Clears the 'type' field, the 'has' method for this field will now return false */
  @Override
  public void clearType() {
    genClient.clear(CacheKey.type);
  }
  /** Clears the 'autoAcceptPaymentConfirmations' field, the 'has' method for this field will now return false */
  @Override
  public void clearAutoAcceptPaymentConfirmations() {
    genClient.clear(CacheKey.autoAcceptPaymentConfirmations);
  }
  /** Clears the 'extras' field, the 'has' method for this field will now return false */
  @Override
  public void clearExtras() {
    genClient.clear(CacheKey.extras);
  }
  /** Clears the 'regionalExtras' field, the 'has' method for this field will now return false */
  @Override
  public void clearRegionalExtras() {
    genClient.clear(CacheKey.regionalExtras);
  }
  /** Clears the 'externalReferenceId' field, the 'has' method for this field will now return false */
  @Override
  public void clearExternalReferenceId() {
    genClient.clear(CacheKey.externalReferenceId);
  }
  /** Clears the 'requestId' field, the 'has' method for this field will now return false */
  @Override
  public void clearRequestId() {
    genClient.clear(CacheKey.requestId);
  }
  /** Clears the 'version' field, the 'has' method for this field will now return false */
  @Override
  public void clearVersion() {
    genClient.clear(CacheKey.version);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public SaleRequest copyChanges() {
    SaleRequest copy = new SaleRequest();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(SaleRequest src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new SaleRequest(src).getJSONObject(), src.genClient);
    }
  }

  public static final android.os.Parcelable.Creator<SaleRequest> CREATOR = new android.os.Parcelable.Creator<SaleRequest>() {
    @Override
    public SaleRequest createFromParcel(android.os.Parcel in) {
      SaleRequest instance = new SaleRequest(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public SaleRequest[] newArray(int size) {
      return new SaleRequest[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<SaleRequest> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<SaleRequest>() {
    @Override
    public SaleRequest create(org.json.JSONObject jsonObject) {
      return new SaleRequest(jsonObject);
    }
  };

  public interface Constraints {

    public static final boolean TIPAMOUNT_IS_REQUIRED = false;
    public static final boolean TIPMODE_IS_REQUIRED = false;
    public static final boolean SIGNATURETHRESHOLD_IS_REQUIRED = false;
    public static final boolean SIGNATUREENTRYLOCATION_IS_REQUIRED = false;
    public static final boolean AUTOACCEPTSIGNATURE_IS_REQUIRED = false;
    public static final boolean ALLOWOFFLINEPAYMENT_IS_REQUIRED = false;
    public static final boolean FORCEOFFLINEPAYMENT_IS_REQUIRED = false;
    public static final boolean DISABLECASHBACK_IS_REQUIRED = false;
    public static final boolean APPROVEOFFLINEPAYMENTWITHOUTPROMPT_IS_REQUIRED = false;
    public static final boolean TAXAMOUNT_IS_REQUIRED = false;
    public static final boolean TIPPABLEAMOUNT_IS_REQUIRED = false;
    public static final boolean TIPSUGGESTIONS_IS_REQUIRED = false;
    public static final boolean ORDERID_IS_REQUIRED = false;
    public static final long ORDERID_MAX_LEN = 13;
    public static final boolean DISABLEPRINTING_IS_REQUIRED = false;
    public static final boolean DISABLERECEIPTSELECTION_IS_REQUIRED = false;
    public static final boolean DISABLEDUPLICATECHECKING_IS_REQUIRED = false;
    public static final boolean CARDNOTPRESENT_IS_REQUIRED = false;
    public static final boolean DISABLERESTARTTRANSACTIONONFAIL_IS_REQUIRED = false;
    public static final boolean AMOUNT_IS_REQUIRED = true;
    public static final boolean CARDENTRYMETHODS_IS_REQUIRED = false;
    public static final boolean VAULTEDCARD_IS_REQUIRED = false;
    public static final boolean EXTERNALID_IS_REQUIRED = true;
    public static final boolean TYPE_IS_REQUIRED = false;
    public static final boolean AUTOACCEPTPAYMENTCONFIRMATIONS_IS_REQUIRED = false;
    public static final boolean EXTRAS_IS_REQUIRED = false;
    public static final boolean REGIONALEXTRAS_IS_REQUIRED = false;
    public static final boolean EXTERNALREFERENCEID_IS_REQUIRED = false;
    public static final boolean REQUESTID_IS_REQUIRED = false;
    public static final long REQUESTID_MAX_LEN = 13;
    public static final boolean VERSION_IS_REQUIRED = false;

  }

}
