/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/*
 * Copyright (C) 2019 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.sdk.v3.onlineorder;

import android.os.Parcelable;
import android.os.Parcel;

/**
 * This is an auto-generated Clover data enum.
 * * `CREATED`: the online order is created
* `CONFIRMED`: the online order is accepted by merchant
* `REJECTED`: the online order is rejected by merchant
* `CANCELLED`: The online order is cancelled
* `IN_PREPARATION`: The online order is being prepared by the merchant.
* `READY_FOR_PICKUP`: Order is ready for pickup
* `IN_TRANSIT`: Order is on the way for delivery
* `FULFILLED`: Order is delivered or picked-up
 */
@SuppressWarnings("all")
public enum OrderState implements Parcelable {
  CREATED, CONFIRMED, REJECTED, CANCELLED, IN_PREPARATION, READY_FOR_PICKUP, IN_TRANSIT, FULFILLED;

  @Override
  public int describeContents() {
    return 0;
  }

  @Override
  public void writeToParcel(final Parcel dest, final int flags) {
    dest.writeString(name());
  }

  public static final Creator<OrderState> CREATOR = new Creator<OrderState>() {
    @Override
    public OrderState createFromParcel(final Parcel source) {
      return OrderState.valueOf(source.readString());
    }

    @Override
    public OrderState[] newArray(final int size) {
      return new OrderState[size];
    }
  };
}
